version: "2.4"
services:
  ui:
    container_name: campsite-ui
    image: dnielsen/campsite:ui
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - postgres
      - "event-service"
  event-service:
    container_name: campsite-event-service
    build: ./packages/event-service
    ports:
      - "4444:4444"
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
      speaker-service:
        condition: service_started
      session-service:
        condition: service_started
    env_file:
      - docker.env
  speaker-service:
    container_name: campsite-speaker-service
    build: ./packages/speaker-service
    ports:
      - "3333:3333"
    restart: always
    env_file:
      - docker.env
    depends_on:
      postgres:
        condition: service_healthy
  session-service:
    container_name: campsite-session-service
    build: ./packages/session-service
    ports:
      - "5555:5555"
    restart: always
    environment:
      - SERVER_PORT=5555
    env_file:
      - docker.env
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
