version: "3"
services:
  event-service:
    container_name: campsite-event-service
    build: ./packages/event-service
    ports:
      - "4444:4444"
    restart: always
    depends_on:
      - postgres
      - "speaker-service"
      - "session-service"
    env_file:
      - docker.env
    networks:
      - app
    expose:
      - 4444
  speaker-service:
    container_name: campsite-speaker-service
    build: ./packages/speaker-service
    ports:
      - "3333:3333"
    restart: always
    env_file:
      - docker.env
    depends_on:
      - postgres
    networks:
      - app
    expose:
      - 3333
  session-service:
    container_name: campsite-session-service
    build: ./packages/session-service
    ports:
      - "5555:5555"
    restart: always
    env_file:
      - docker.env
    depends_on:
      - postgres
    networks:
      - app
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    env_file:
      - docker.env
    networks:
      - app
  pgadmin:
    links:
      - postgres
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - "8080:80"
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin/
    env_file:
      - docker.env
    networks:
      - app
networks:
  app:
    driver: bridge
