version: "3"
services:
#  server:
#    container_name: campsite-server
#    build: ./packages/server
#    ports:
#      - "4444:4444"
#    restart: always
#    networks:
#      - app
#    depends_on:
#      - postgres
#    env_file:
#      - docker.env
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    env_file:
      - docker.env
    networks:
      - app
  pgadmin:
    links:
      - postgres
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - "8080:80"
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin/
    env_file:
      - docker.env
    networks:
      - app
networks:
  app:
    driver: bridge
