version: "2.4"
services:
  ui:
    container_name: campsite-ui
    image: dnielsen/campsite:ui
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - server
  server:
    container_name: campsite-server
    build: server
    ports:
      - "4444:4444"
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - docker.env
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    env_file:
      - docker.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
