db:
  name: postgres
  user: postgres
  password: postgres
  host: localhost
  port: 5432
  sslmode: disable
server:
  address: 0.0.0.0:4444
service:
  session:
    address: http://localhost:5555
  speaker:
    address: http://localhost:3333