db:
  name: postgres
  user: postgres
  password: postgres
  host: localhost
  port: 5432
  sslmode: disable
service:
  session:
    host: localhost
    port: 5555
  event:
    host: localhost
    port: 4444
  speaker:
    host: localhost
    port: 3333